/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GeneralTable: typeof import('./src/components/table/GeneralTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/sidebar/SideBar.vue')['default']
    SideBarSection: typeof import('./src/components/sidebar/SideBarSection.vue')['default']
    ThemeButton: typeof import('./src/components/ThemeButton.vue')['default']
  }
}
